language: node_js
node_js:
  - "8.10"
before_script: echo $TEST_API_URL && if [ $TRAVIS_PULL_REQUEST != "false" ]; then export TEST_API_URL="https://scout-stage-pr-$TRAVIS_PULL_REQUEST.herokuapp.com"; fi && echo $TEST_API_URL
script: npm install && sleep 30 && npm test
